title: LTG's URL Shortener (Powered by Jekyll)
description: The official URL shortener of LaroTayoGaming
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug/

plugins:
  - jekyll-redirect-from

repository: LaroTayoGaming/url-shortener
